### ISSUE TITLE
Extra </code> tag added to the end of the highlighted text

### ISSUE THREAD

**Issue by mgibbs189** [trentrichardson/jQuery-Litelighter#1]
Hi,

When using

```
$('pre').litelighter();
```

On HTML code that looks like this:

```
<pre><code>[...some actual code...]</code></pre>
```

An extra closing </code> tag gets printed to the bottom of the highlighted text.

See this screenshot: http://i.imgur.com/Qhygv.png

**Comment by trentrichardson** [comment]
Yeah it actually isn't expecting the inner code tags.  Just pre will do. I was hoping to have litelighter work on any type element.  If the code tag is there for backwards compatiblity you may add a couple lines to strip it out:

``` js
$('pre').each(function(i,obj){
    var $t = $(this),
        $code = $t.children('code'),
        tmpcode = "";

    if($code.length > 0){
        tmpcode = $code.text();
        $code.remove();
        $t.text(tmpcode);
    }
}).litelighter();
```

**Comment by mgibbs189** [comment]
Right, that's a good workaround.

I just wanted to point it out, in case it was an edge case litelighter was supposed to handle.
